### ISSUE TITLE
Need more information

### ISSUE THREAD

**Issue by youngfish42** [lxcnju/FedPS-AggregateOrNot#1]
Many thanks to the author for open sourcing this work :heart: , but the current source code is missing some parts, such as environment dependencies and dataset fetching, as well as some mismatches between the filenames declared in the readme and the actual filenames(e.g. `train_ps_auto.py` and `train_fedps_auto.py`) .

**Comment by lxcnju** [comment]
Thanks for the suggestions! We have added the running packages and the dataset links.
